# SPDX-License-Identifier: MIT

"""Generate deterministic C++17 inline arrays for embedded web/audio assets."""

from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.


PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
BUILD_DIR = Path(env.subst("$BUILD_DIR"))
OUTPUT = BUILD_DIR / "generated" / "embedded_assets.h"
env.Append(CPPPATH=[str(BUILD_DIR)])


def format_bytes(data: bytes, width: int = 16) -> str:
    rows = []
    for offset in range(0, len(data), width):
        chunk = data[offset : offset + width]
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(rows)


def generate() -> str:
    boot = (PROJECT_DIR / "src" / "assets" / "sfx" / "boot_sfx.bin").read_bytes()
    html = (PROJECT_DIR / "src" / "assets" / "web" / "badge_config_ap.html").read_bytes()
    return f"""// Generated by scripts/generate_embedded.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace embedded_assets {{

alignas(4) inline constexpr std::uint8_t bootSfx[] = {{
{format_bytes(boot)}
}};
inline constexpr std::size_t bootSfxSize = sizeof(bootSfx);

inline constexpr std::uint8_t badgeConfigHtml[] = {{
{format_bytes(html)}
}};
inline constexpr std::size_t badgeConfigHtmlSize = sizeof(badgeConfigHtml);

}}  // namespace embedded_assets
"""


OUTPUT.parent.mkdir(parents=True, exist_ok=True)
content = generate()
if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
    OUTPUT.write_text(content, encoding="utf-8")
